### PR TITLE
Allow for Header/Footer in PDF rendering

### PR DESCRIPTION
**Pull request by avnersorek**
As shown in the PhantomJS example - https://github.com/ariya/phantomjs/blob/master/examples/printheaderfooter.js

### CODE REVIEW

**Comment by romanlab** [comment]
We really need this. When will this be merged?

**Comment by SamMorrowDrums** [comment]
@e-conomic is it possible to merge some of the PR work, or possibly offer the repo to potential new maintainers? Great project - it deserves to stay alive.

**Comment by markstos** [comment]
@SamMorrowDrums As someone who has become a co-maintainer of several of open source projects, here's the process I recommend:

In your Github fork, merge all the contributions from other forks and PRs that make sense for the next release. Update the Changelogs, bump the versions and otherwise completely compare a branch for the next release.  Then ask the maintainers if they'd like to release it as the next version. You've made the job really easy since the release is ready to go if they approve. If they don't agree or don't respond, release your version under a new name.

I think adding one or more new co-maintainers to the project would be the best option to spread the work around, but sometimes that just doesn't pan out.

**Comment by SamMorrowDrums** [comment]
Great advice @markstos!

**Comment by SamMorrowDrums** [comment]
OK, so I've looked at and merged the current PRs - they all look good - or do important things. I'd love it if anyone wanted to test / add any new tests if coverage isn't sufficient.

Once we are happy @markstos I can tag and ping the owners. Creating an issue now.

**Pull request merged**
